package com.lokapos.enums;

public enum RESPONSE_ENUM {
    SIGN_IN_FAILED, NOT_AUTHORIZED, SUCCESS, OTP_INVALID, NOT_FOUND_OTP, OTP_EXPIRED, ACCOUNT_HAVE_BUSINESS, PROVINCE_NOT_FOUND, CITY_NOT_FOUND, DISTRICT_NOT_FOUND, SUB_DISTRICT_NOT_FOUND, INVALID_CREDENTIAL, ACCOUNT_DONT_HAVE_BUSINESS, PACKAGE_NOT_FOUND, CATEGORY_NOT_FOUND, CATEGORY_AND_BUSINESS_NOT_MATCH, ORDER_NOT_FOUND, MENU_NOT_FOUND, EMAIL_ALREADY_EXIST
}
