name: Manual Deploy - Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to (e.g., staging or production)'
        required: true
        default: 'staging'
        # Add options for other environments if needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: ./mvnw package -DskipTests=true -Dspring-boot.run.profiles=server

  deploy-server-1:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' # Trigger only if manually dispatched
    steps:
      - name: RUNNING DEPLOY SERVER 1
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
            ls
            systemctl status app
            sudo systemctl stop app
            sudo systemctl status app
            echo ================= SERVER 1 STOP APPLICATION SUCCESS =================
            cd app
            ls
            git checkout development
            git pull origin development
            echo ================= SERVER 1 PULL SUCCESS =================
            mvn clean install
            echo INSTALL SUCCESS
            ./mvnw package -DskipTests=true
            sudo systemctl start app
            echo ================= START SUCCESS =================
            sudo systemctl status app
            echo ================= SERVER 1 DEPLOYING SUCCESS SERVER 1 =================